In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [8]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [10]:
mat =np.matrix(l)

In [11]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [12]:
 a = arr

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
arr[0] = 100

In [15]:
arr

array([100,   2,   3,   4,   5])

In [16]:
a

array([100,   2,   3,   4,   5])

In [17]:
b = np.copy(arr)

In [18]:
arr[0]=10

In [19]:
b

array([100,   2,   3,   4,   5])

In [20]:
arr

array([10,  2,  3,  4,  5])

In [21]:
#a make shallow copy and b make a deep copy

In [22]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
list(i*i for i in range(6))

[0, 1, 4, 9, 16, 25]

In [25]:
iterable =(i*i for i in range(6))

In [26]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [27]:
np.fromstring('23 45 32',sep =' ')

array([23., 45., 32.])

In [28]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr1.size

6

In [30]:
arr1.shape

(2, 3)

In [31]:
arr.dtype

dtype('int64')

In [32]:
list(range(5))

[0, 1, 2, 3, 4]

In [33]:
list(range(0.5,9.5))

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
np.arange(0.5,9.5)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5])

In [35]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [36]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((2,3,2,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [40]:
np.diagonal((5,3))

ValueError: diag requires an array of at least two dimensions

In [41]:
arr

array([10,  2,  3,  4,  5])

In [42]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
arr1=np.eye(5)

In [44]:
import pandas as pd

In [45]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [46]:
np.random.rand(2,3)

array([[0.52676612, 0.91489271, 0.6159959 ],
       [0.64688361, 0.14401568, 0.27894681]])

In [47]:
np.random.randn(2,3)

array([[ 0.93517306, -0.08435494, -0.17661532],
       [ 0.13334843,  1.10482112,  0.3571166 ]])

In [48]:
arr2=np.random.randint(1,5,(2,3))

In [49]:
arr2.size

6

In [50]:
arr2.dtype

dtype('int64')

In [51]:
arr2.shape

(2, 3)

In [52]:
arr2.reshape(3,2)

array([[2, 1],
       [1, 4],
       [3, 4]])

In [53]:
arr2.reshape(3,-1)

array([[2, 1],
       [1, 4],
       [3, 4]])

In [54]:
arr1 = np.random.randint(1,10,(5,6))

In [55]:
arr1

array([[7, 6, 3, 7, 9, 4],
       [2, 1, 6, 2, 6, 7],
       [3, 1, 7, 1, 5, 8],
       [5, 7, 8, 7, 4, 7],
       [3, 9, 5, 4, 1, 4]])

In [56]:
arr1>8

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [57]:
arr1[arr1>8]

array([9, 9])

In [58]:
arr1[2:4,[2,3]]

array([[7, 1],
       [8, 7]])

In [59]:


arr1 =np.random.randint(1,5,(3,3))

In [60]:
arr2=np.random.randint(1,5,(3,3))

In [61]:
arr1

array([[2, 2, 4],
       [2, 4, 1],
       [2, 3, 4]])

In [62]:
arr2

array([[3, 1, 2],
       [3, 3, 4],
       [4, 4, 1]])

In [63]:
arr1+arr2

array([[5, 3, 6],
       [5, 7, 5],
       [6, 7, 5]])

In [64]:
#index multiplication
arr1*arr2

array([[ 6,  2,  8],
       [ 6, 12,  4],
       [ 8, 12,  4]])

In [65]:
#matrix multiplication
arr1@arr2

array([[28, 24, 16],
       [22, 18, 21],
       [31, 27, 20]])

In [66]:
arr1/arr2

array([[0.66666667, 2.        , 2.        ],
       [0.66666667, 1.33333333, 0.25      ],
       [0.5       , 0.75      , 4.        ]])

In [67]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [68]:
#numpy -broadcasting

In [69]:
arr = np.zeros((3,4))

In [70]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [72]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [73]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [74]:
b = np.array([[3,4,5]])

In [75]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [ ]:
arr+b.T

In [76]:
b.T

array([[3],
       [4],
       [5]])

In [77]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 2.        ],
       [1.41421356, 2.        , 1.        ],
       [1.41421356, 1.73205081, 2.        ]])

In [78]:
arr1

array([[2, 2, 4],
       [2, 4, 1],
       [2, 3, 4]])

In [79]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.60205999],
       [0.30103   , 0.60205999, 0.        ],
       [0.30103   , 0.47712125, 0.60205999]])

In [80]:
np.exp(arr1)

array([[ 7.3890561 ,  7.3890561 , 54.59815003],
       [ 7.3890561 , 54.59815003,  2.71828183],
       [ 7.3890561 , 20.08553692, 54.59815003]])

In [81]:
np.max(arr1)

4

In [82]:
#numpy- array manipulation.

In [83]:
arr = np.random.randint(1,10,(4,4))

In [84]:
arr

array([[2, 5, 9, 6],
       [7, 2, 2, 7],
       [1, 2, 4, 3],
       [6, 5, 5, 7]])

In [85]:
arr.T

array([[2, 7, 1, 6],
       [5, 2, 2, 5],
       [9, 2, 4, 5],
       [6, 7, 3, 7]])

In [86]:
arr.flatten()

array([2, 5, 9, 6, 7, 2, 2, 7, 1, 2, 4, 3, 6, 5, 5, 7])

In [87]:
np.expand_dims(arr,axis=0)

array([[[2, 5, 9, 6],
        [7, 2, 2, 7],
        [1, 2, 4, 3],
        [6, 5, 5, 7]]])

In [88]:
np.expand_dims(arr,axis=1)

array([[[2, 5, 9, 6]],

       [[7, 2, 2, 7]],

       [[1, 2, 4, 3]],

       [[6, 5, 5, 7]]])

In [2]:
data = np.array([[1],[2],[3]])

In [3]:
data

array([[1],
       [2],
       [3]])

In [4]:
np.squeeze(data)

array([1, 2, 3])

In [5]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [6]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [7]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [9]:
arr1

array([[9, 5, 8, 3],
       [4, 5, 1, 5],
       [5, 3, 7, 4]])

In [10]:
arr2

array([[6, 9, 5, 1],
       [7, 9, 9, 2],
       [1, 4, 5, 8]])

In [11]:
arr1-arr2

array([[ 3, -4,  3,  2],
       [-3, -4, -8,  3],
       [ 4, -1,  2, -4]])

In [12]:
#numpy string function

In [13]:
arr = np.array(['sudh','kumar'])

In [14]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [15]:
np.char.lower(arr)

array(['sudh', 'kumar'], dtype='<U5')

In [16]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [18]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [19]:
#numpy Mathematical function

In [21]:
arr1

array([[9, 5, 8, 3],
       [4, 5, 1, 5],
       [5, 3, 7, 4]])

In [22]:
np.sin(arr1)

array([[ 0.41211849, -0.95892427,  0.98935825,  0.14112001],
       [-0.7568025 , -0.95892427,  0.84147098, -0.95892427],
       [-0.95892427,  0.14112001,  0.6569866 , -0.7568025 ]])

In [23]:
np.tan(arr1)

array([[-0.45231566, -3.38051501, -6.79971146, -0.14254654],
       [ 1.15782128, -3.38051501,  1.55740772, -3.38051501],
       [-3.38051501, -0.14254654,  0.87144798,  1.15782128]])

In [24]:
np.power(arr1,2)

array([[81, 25, 64,  9],
       [16, 25,  1, 25],
       [25,  9, 49, 16]])

In [25]:
np.median(arr1)

5.0

In [27]:
np.std(arr1)

2.1392496088322392

In [30]:
np.var(arr1)

4.576388888888889

In [31]:
#numpy arthimetic  operatiom

In [33]:
np.subtract(arr1,arr2)

array([[ 3, -4,  3,  2],
       [-3, -4, -8,  3],
       [ 4, -1,  2, -4]])

In [34]:
np.multiply(arr1,arr2)

array([[54, 45, 40,  3],
       [28, 45,  9, 10],
       [ 5, 12, 35, 32]])

In [39]:
arr=np.array([3,5,2,6,4])

In [38]:
arr

array([3, 5, 2, 6, 4])

In [40]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [41]:
np.searchsorted(arr,3)

3

In [42]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [43]:
np.count_nonzero(arr1)

6

In [44]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9]),)

In [47]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

In [48]:
#numpy - byte swapping

In [50]:
arr1.byteswap()

array([                   0,  4900197869555810304, -8862521116711714816,
        4683743612465315840,   432345564227567616,   432345564227567616,
                          0,                    0,                    0,
       -1585267068834414592])

In [51]:
b = arr1.view()

In [52]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [53]:
b[0]=234

In [54]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [55]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [56]:
#numpy - matrix libary

In [57]:
import numpy.matlib as nm

In [58]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [59]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [62]:
arr1 =np

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [63]:
arr2

array([[6, 9, 5, 1],
       [7, 9, 9, 2],
       [1, 4, 5, 8]])